function paperPlotPerforatePressureDrop()
    [expD1N28d20RPM420DataCells,expD1N28d20RPM420CombineData] ...
		= loadExpDataFromFolder('e:\netdisk\shareCloud\【大论文】\[04]数据\实验原始数据\内插孔管\D1N28d20RPM420两头堵');
    [exp1DDataCells,exp1DCombineData] ...
		= loadExpDataFromFolder('e:\netdisk\shareCloud\【大论文】\[04]数据\实验原始数据\内插管\内插管1D罐中间420转0.05mpa');
    [exp1DODataCells,exp1DOCombineData] ...
		= loadExpDataFromFolder('e:\netdisk\shareCloud\【大论文】\[04]数据\实验原始数据\内置孔板\D1RPM420罐中间');
    [exp1DO3DataCells,exp1DO3CombineData] ...
		= loadExpDataFromFolder('e:\netdisk\shareCloud\【大论文】\[04]数据\实验原始数据\内置孔板\D1RPM420罐3块');
    figureExpPressureDrop({exp1DCombineData,expD1N28d20RPM420CombineData,exp1DOCombineData,exp1DO3CombineData}...
        ,{'内插管1D','内插孔管1D','内插孔板1D','内插孔板1D三块'}...
        ,[2,3]...
        ,'chartType','bar');
end