function paperPlotInnerPipeExpCmp(innerPipeDataCells,legendLabels,isSaveFigure)
%内插管的实验对比
    errorType = 'ci';
    errorPlotType = 'bar';
    figureHeight = 6;
    rang = 1:13;
    figure();
    paperFigureSet('small',figureHeight);
    fh = figureExpPressurePlus(innerPipeDataCells,legendLabels...
        ,'errorType',errorType...
        ,'rang',rang...
        ,'showPureVessel',true ...
        ,'purevessellegend','缓冲罐'...
        ,'showVesselRegion',true...
        ,'errorPlotType',errorPlotType...
        ,'showMeasurePoint',true...
        ,'isFigure',false...
        ,'markerStyle','point'...
        );
    box on;
    fixSmallFigurePosition(fh);
    if isSaveFigure
        set(gca,'color','none');
		saveFigure(fullfile(getPlotOutputPath(),'ch06'),'内插管-实验压力脉动对比');
	end
    
    figure();
    paperFigureSet('small',figureHeight);
    [base,err] = loadExpStandardVesselData();
    base = base(rang);
    err = err(rang);
    fh = figureExpPressurePlusSuppressionRate(innerPipeDataCells...     
                    ,legendLabels...
                    ,'errorPlotType','bar'...
                    ,'showVesselRigon',1 ...
                    ,'suppressionRateBase',{base}...
                    ,'suppressionRateBaseErr',err...
                    ,'xIsMeasurePoint',0 ...
                    ,'figureHeight',6 ...
                    ,'xlabelText','管线距离(m)'...
                    ,'ylabelText','压力脉动抑制率(%)'...
                    ,'isFigure',0 ...
                    ,'rangs',rang...
                    ,'markerStyle','point'...
                    ,'ylim',[-20,100]...
                    );
    fixSmallFigurePosition(fh);
    set(fh.legend,'Position',[0.157058599695586 0.573263895197047 0.322574197348701 0.241064808506657]);


    for i = 1:length(fh.measurePointGrid)
        set(fh.measurePointGrid(i),'LineStyle',':');
    end  

    if isSaveFigure
		saveFigure(fullfile(getPlotOutputPath(),'ch06'),'内插管-实验抑制率对比');
	end
end
