function paperPlotInnerPipeExpCmp(innerPipeDataCells,legendLabels,isSaveFigure)
%内插管的实验对比
    errorType = 'ci';
    figureExpPressurePlusAndSuppressionRate(innerPipeDataCells,legendLabels...
        ,'showPureVessel',true...
        ,'showVesselRegion',true...
        ,'errorType',errorType...
        ,'y2lim',[-20,120]...
        );

    if isSaveFigure
		saveFigure(fullfile(getPlotOutputPath(),'ch06'),'内插管-实验压力脉动-抑制率对比');
	end
end
