%% 第五章 绘图 - 单一缓冲罐理论扩展分析
clear all;
close all;
clc;

freRaw = [7,14,21,28,14*3];
massFlowERaw = [0.02,0.2,0.03,0.003,0.007];
Dpipe = 0.098;
Dv = 0.372;
%% 
Vmin = pi* Dpipe^2 / 4 * 1.1 *1.5;
Vmid = pi* Dv^2 / 4 * 1.1;
Vmax = Vmid*3;
V = Vmin:0.02:Vmax;
theoryDataCellsChangVolume = oneVesselChangVolume(V,'massflowdata',[freRaw;massFlowERaw]...
                                                    );
resChangVolume = theoryDataCellsChangVolume(2:end,2);
XChangVolume = theoryDataCellsChangVolume(2:end,3);
fh = figureTheoryPressurePlus(resChangVolume,XChangVolume,'Y',V...
    ,'yLabelText','体积'...
    ,'chartType','surf'...
    ,'edgeColor','none'...
    ,'sectionY',Vmid...
    ,'markSectionY','all'...
    ,'markSectionYLabel',{'a'}...
    ,'sectionX',10 ...
    ,'markSectionX','all'...
    ,'markSectionXLabel',{'b'}...
    ,'fixAxis',1 ...
);
view(-161,37);
highLowColorbar();                                        
%% 单一缓冲罐变长径比对气流脉动的影响

Lv = 0.5:0.1:3;


theoryDataCellsChangLengthDiameterRatio = oneVesselChangLengthDiameterRatio('massflowdata',[freRaw;massFlowERaw]...
                                                    ,'Lv',Lv...
                                                    );
resChangLengthDiameterRatio = theoryDataCellsChangLengthDiameterRatio(2:end,2);
XChangLengthDiameterRatio = theoryDataCellsChangLengthDiameterRatio(2:end,3);
r = 1.1 / 0.372;
for i=2:size(theoryDataCellsChangLengthDiameterRatio,1)
   % labels{i-1} = sprintf('%g,(Lv:%g)',theoryDataCellsChangLengthDiameterRatio{i,6},theoryDataCellsChangLengthDiameterRatio{i,4});
    YChangLengthDiameterRatio(i-1) = theoryDataCellsChangLengthDiameterRatio{i,6};
end
fh = figureTheoryPressurePlus(resChangLengthDiameterRatio,XChangLengthDiameterRatio...
    ,'Y',YChangLengthDiameterRatio...
    ,'yLabelText','长径比'...
    ,'chartType','surf'...
    ,'edgeColor','none'...
    ,'sectionY',r...
    ,'markSectionY','all'...
    ,'markSectionYLabel',{'a'}...
);
view(-41,20);
highLowColorbar();