function paperPlotSingleVesselTheIteChangL1(param,massFlowData,isSaveFigure)
%µü´ú»º³å¹ÞÎ»ÖÃ
%chartType = 'surf';
    chartType = 'contourf';
    L1 = 0:0.1:8;
    
    theoryDataCellsChangL1 = oneVesselChangL1FixL(L1,param.L...
        ,'vType','straightInBiasOut'...
        ,'massflowdata',massFlowData...
        ,'param',param);
    %x
    xCells = theoryDataCellsChangL1(2:end,3);
    %y
    zCells = theoryDataCellsChangL1(2:end,2);
    fh = figureTheoryPressurePlus(zCells,xCells,'Y',L1...
        ,'yLabelText','L1'...
        ,'chartType',chartType...
        ,'fixAxis',1 ...
        ,'edgeColor','none'...
        ,'sectionY',param.L1...
        ,'markSectionY','all'...
        ,'markSectionYLabel',{'a'}...
        );
    ch = colorbar();
    set(get(ch,'Label'),'String','Ñ¹Á¦Âö¶¯·å·åÖµ(kPa)');
    colormap jet;
	if isSaveFigure
		set(gca,'color','none');
		saveFigure(fullfile(getPlotOutputPath(),'ch05'),'Ö±½ø²à³ö»º³å¹Þµü´ú»º³å¹ÞÎ»ÖÃ');
	end
end
