function [ output_args ] = paperPlotSingleVesselExpSuppressionRateResult( vesselDirectInDirectOutCombineData,vesselSuppressionRateCells,legendSuppressionRateLabels,isSaveFigure )
%绘制缓冲罐实验和直管的脉动抑制率
    [ ddMean,~,~,~,muci,~ ] = getExpCombineReadedPlusData(vesselDirectInDirectOutCombineData);
    ddMean = ddMean(1:13);
    suppressionRateBase = ddMean;
    suppressionRateBaseErr = muci(2,1:13) - ddMean;
    xlabelText = '距离(m)';
    ylabelText = '脉动抑制率(%)';
    figure
    paperFigureSet('small',6);
    fh = figureExpPressurePlusSuppressionRate(vesselSuppressionRateCells...
            ,legendSuppressionRateLabels...        
            ,'errorPlotType','bar'...
            ,'showVesselRigon',0 ...
            ,'suppressionRateBase',suppressionRateBase...
            ,'suppressionRateBaseErr',suppressionRateBaseErr...
            ,'xIsMeasurePoint',0 ...
            ,'figureHeight',8 ...
            ,'xlabelText',xlabelText...
            ,'ylabelText',ylabelText...
            ,'isFigure',false...
            ,'ylim',[-20,40]...
            );
    fixSmallFigurePosition();
    set(fh.legend,...
        'Position',[0.471478364339335 0.570824799738908 0.521917798713734 0.241064808506657]);
    if isSaveFigure
        set(gca,'color','none');
		saveFigure(fullfile(getPlotOutputPath(),'ch05'),'实验缓冲罐对直进直出的脉动抑制率');
	end


end

