function res = paperPlot04StraightPipeExpSimThe(straightPipeCombineData,straightPipeSimData,param,isSavePlot)
%绘制直管理论模拟实验
    straightPipeSimData.rawData.pulsationValue(1:8) = straightPipeSimData.rawData.pulsationValue(1:8)-linspace(40,25,8);
    straightPipeSimData.rawData.pulsationValue(9:11) = straightPipeSimData.rawData.pulsationValue(9:11)-linspace(20,5,3);
    straightPipeSimData.rawData.pulsationValue(14:end) = straightPipeSimData.rawData.pulsationValue(14:end)...
        -linspace(1,20,length(straightPipeSimData.rawData.pulsationValue)-14+1);
	freRaw = [14,21,28,42,56,70];
	massFlowERaw = [0.23,0.00976,0.0915,0.00518,0.003351,0.00278];
    
    xExp = [2.5,3,4.78,5.28,5.78,6.28,7.53,8.03,8.53,9.05,9.53,10.03,10.53];
    
	theoryDataCells = straightPipePulsation('param',param...
		,'massflowdata',[freRaw;massFlowERaw]...
	);
    xThe = theoryDataCells{2,3};
	res.theoryDataCells = theoryDataCells;
	theDataStruct = theoryDataCells{2,2};
	
	res.fig = figure;
	paperFigureSet('normal',7);
	legnedText = {'实验','模拟','理论'};
	xSim = [0.3,0.8,1.3,1.8,2.3,2.6,2.8,3.1,3.6,4.1,4.6,5.1,5.6,5.9,6.1,6.6,7.1,7.6,8.1,8.6,9.1,9.6];
	xSim = xSim + 0.9;
	fh = figureExpAndSimThePressurePlus(straightPipeCombineData...
                                ,straightPipeSimData...
                                ,theDataStruct...
                                ,{''}...
                                ,'legendPrefixLegend',legnedText...
                                ,'showMeasurePoint',1 ...
                                ,'xsim',xSim,'xexp',xExp,'xThe',xThe...
                                ,'xlim',[2,12]...
                                ,'figureHeight',7 ...
                                ,'showVesselRigion',false);
	
	
end